# Generated by Django 2.1.4 on 2018-12-10 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=50, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('host_model', models.CharField(blank=True, max_length=50)),
                ('under_warranty', models.BooleanField(blank=True)),
                ('nerwork_adapter_speed', models.CharField(blank=True, max_length=50)),
                ('network_adapters', models.PositiveSmallIntegerField(blank=True)),
                ('processor_type', models.CharField(blank=True, max_length=50)),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True)),
                ('Hyperthreading', models.BooleanField(blank=True)),
                ('memory', models.PositiveSmallIntegerField(blank=True)),
                ('storage_capacity', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'Hosts',
            },
        ),
    ]
