# Generated by Django 2.1.4 on 2018-12-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='Host',
        ),
    ]
