# Generated by Django 2.1.4 on 2018-12-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0002_auto_20181210_0949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
