# Generated by Django 2.1.4 on 2018-12-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0003_auto_20181210_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='host_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='under_warranty',
            new_name='warranty',
        ),
    ]
