# Generated by Django 2.1.4 on 2018-12-24 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0004_auto_20181210_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='Hyperthreading',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='host',
            name='nerwork_adapter_speed',
        ),
        migrations.AddField(
            model_name='host',
            name='disk_number',
            field=models.PositiveSmallIntegerField(blank=True, db_column='disk_number', null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disk_type',
            field=models.CharField(blank=True, db_column='disk_type', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='hyperthreading',
            field=models.BooleanField(blank=True, db_column='hyperthreading', default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='host',
            name='network_adapter_speed',
            field=models.CharField(blank=True, db_column='network_adapter_speed', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='raid_type',
            field=models.CharField(blank=True, db_column='raid_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, db_column='cpu_cores', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.PositiveSmallIntegerField(blank=True, db_column='memory', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='model',
            field=models.CharField(db_column='model', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(db_column='name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='network_adapters',
            field=models.PositiveSmallIntegerField(blank=True, db_column='network_adapters', default=1),
        ),
        migrations.AlterField(
            model_name='host',
            name='processor_type',
            field=models.CharField(blank=True, db_column='processor_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='serial_number',
            field=models.CharField(db_column='serial_number', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='storage_capacity',
            field=models.CharField(blank=True, db_column='storage_capacity', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor',
            field=models.CharField(db_column='vendor', max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='warranty',
            field=models.BooleanField(db_column='warranty', default=False),
        ),
    ]
