# Generated by Django 2.1.4 on 2018-12-25 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0006_auto_20181224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, db_column='cpu_cores', null=True, verbose_name='处理器核心数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_number',
            field=models.PositiveSmallIntegerField(blank=True, db_column='disk_number', null=True, verbose_name='磁盘数量'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_type',
            field=models.CharField(blank=True, db_column='disk_type', max_length=50, verbose_name='磁盘类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hyperthreading',
            field=models.BooleanField(blank=True, db_column='hyperthreading', default=False, verbose_name='处理器是否支持超线程'),
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='服务器ID'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.PositiveSmallIntegerField(blank=True, db_column='memory', null=True, verbose_name='服务器内存大小'),
        ),
        migrations.AlterField(
            model_name='host',
            name='model',
            field=models.CharField(db_column='model', max_length=50, verbose_name='服务器型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(db_column='name', max_length=50, unique=True, verbose_name='服务器名称'),
        ),
        migrations.AlterField(
            model_name='host',
            name='network_adapter_speed',
            field=models.CharField(blank=True, db_column='network_adapter_speed', max_length=50, verbose_name='服务器网卡速率'),
        ),
        migrations.AlterField(
            model_name='host',
            name='network_adapters',
            field=models.PositiveSmallIntegerField(blank=True, db_column='network_adapters', null=True, verbose_name='服务器网卡数量'),
        ),
        migrations.AlterField(
            model_name='host',
            name='processor_type',
            field=models.CharField(blank=True, db_column='processor_type', max_length=50, verbose_name='服务器处理器型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='raid_type',
            field=models.CharField(blank=True, db_column='raid_type', max_length=50, verbose_name='磁盘RAID'),
        ),
        migrations.AlterField(
            model_name='host',
            name='serial_number',
            field=models.CharField(db_column='serial_number', max_length=50, verbose_name='服务器序列号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='storage_capacity',
            field=models.PositiveSmallIntegerField(blank=True, db_column='storage_capacity', null=True, verbose_name='存储容量'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor',
            field=models.CharField(db_column='vendor', max_length=50, verbose_name='服务器厂商'),
        ),
        migrations.AlterField(
            model_name='host',
            name='warranty',
            field=models.BooleanField(db_column='warranty', default=False, verbose_name='服务器是否在保'),
        ),
    ]
