# Generated by Django 2.1.4 on 2018-12-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosts', '0007_auto_20181225_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ssd_capacity',
            field=models.PositiveSmallIntegerField(blank=True, db_column='ssd_capacity', null=True, verbose_name='SSD容量'),
        ),
    ]
